language: node_js
sudo: required
node_js:
  - 4.2.3
matrix:
  fast_finish: true
  allow_failures:
    - node_js: 5.1.1
before_script:
  - npm install -g bower grunt-cli
  - gem install sass
  - bower install
  - chmod +x .travis-script.sh
services:
  - mongodb
  - docker
before_install:
  - docker login -e="$DOCKER_EMAIL" -u="$DOCKER_USERNAME" -p="$DOCKER_PASSWORD" tutum.co
script: ./.travis-script.sh
